version: '3.1'

services:
  next_js_www:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:8080
    # env_file:
    #   - ./.env
    volumes:
      - ./:/var/app
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
